---
# tasks file for gctech
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present

    - name: Change Apache listen port to 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        line: 'Listen 8080'

    - name: Copy index.html to web root
      copy:
        src:  index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'

    - name: Start and enable httpd service
      service:
        name: httpd
        state: restarted
        enabled: yes
